/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: b76706f8fdf2de67796809f39728d619)
interface __BaseEnv_Env {
  AI: Ai;
  GRADIUM_API_KEY: string;
  VoiceChatAgent: DurableObjectNamespace<import("./src/server").VoiceChatAgent>;
  TranslateAgent: DurableObjectNamespace<import("./src/server").TranslateAgent>;
  VoiceDesignAgent: DurableObjectNamespace<
    import("./src/server").VoiceDesignAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "VoiceChatAgent" | "TranslateAgent" | "VoiceDesignAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "GRADIUM_API_KEY">
  > {}
}
